[pytest]
pythonpath = .
filterwarnings =
    error::pytest.PytestUnhandledThreadExceptionWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated; install `httpx2` instead\.:Warning
    ignore:pkg_resources is deprecated as an API:UserWarning:jieba\._compat
